export default function fakeResponse() {
    return [  
  
    {    
        id: 1,    
        frase: "Regras são feitas para serem quebradas igual predios ou pessoas",    
        alternativas: ["Jinx", "Zyra", "Vi", "Garen"],
        resposta: "Jinx"
    },

    {
        id: 2,
        frase: "Não me deixe triste, escolha um bom caixão.",
        alternativas: ["Yorick", "Mordekaiser", "Karthus", "Sion"],
        resposta: "Karthus"
    },

    {
        id: 3,
        frase: "Minhas mãos estão manchadas de sangue, assim como minha alma.",
        alternativas: ["Darius", "Kled", "Olaf", "Draven"],
        resposta: "Darius"
    },

    {
        id: 4,
        frase: "Acredite em mim, meu coração é como um relógio.",
        alternativas: ["Ekko", "Zac", "Heimerdinger", "Ziggs"],
        resposta: "Ekko"
    },

    {
        id: 5,
        frase: "Mãe disse para sempre proteger as árvores.",
        alternativas: ["Maokai", "Ivern", "Zac", "Elise"],
        resposta: "Ivern"
    },

    {
        id: 6,
        frase: "Céus, são muitas estrelas! Ugh, agora tenho que contar de novo...",
        alternativas: ["Bard", "Aurelion Sol", "Kindred", "Zoe"],
        resposta: "Aurelion Sol"
    },

    {
        id: 7,
        frase: "Viver é morrer, escolha uma e vá com ela.",
        alternativas: ["Kalista", "Thresh", "Hecarim", "Karthus"],
        resposta: "Karthus"
    },

    {
        id: 8,
        frase: "Uma nova estratégia é necessária.",
        alternativas: ["Swain", "LeBlanc", "Gangplank", "Talon"],
        resposta: "Swain"
    },

    {
        id: 9,
        frase: "Foco na batalha que você já perdeu, e você nunca vencerá.",
        alternativas: ["Garen", "Jarvan IV", "Xin Zhao", "Aatrox"],
        resposta: "Aatrox"
    },
    
    {
        id: 10,
        frase: "Lentamente, como a chuva, a névoa negra invade o meu pensamento.",
        alternativas: ["Evelynn", "Nocturne", "Shaco", "Twitch"],
        resposta: "Nocturne"
    }
]

}